### ISSUE TITLE
Families like "kameleon" or "streamline-colors" are impossible to install

### ISSUE THREAD

**Issue by dmandrioli** [webalys-hq/streamlinehq-npm#27]
Hi,

Installing families given as example in the documentation works well but when I try to install other families like "kameleon" or "streamline-colors" I get this kind of error.

```
npm ERR! Installing Streamline assets for kameleon families
npm ERR! Error
npm ERR! Error: Got error "unable to process request at this time"
npm ERR!     at /home/hail/icons/node_modules/@streamlinehq/streamlinehq/build/index.js:1:4437
npm ERR!     at /home/hail/icons/node_modules/@streamlinehq/streamlinehq/build/index.js:1:1702
npm ERR!     at Object.next (/home/hail/icons/node_modules/@streamlinehq/streamlinehq/build/index.js:1:1807)
npm ERR!     at i (/home/hail/icons/node_modules/@streamlinehq/streamlinehq/build/index.js:1:546)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

I firstly tough to a trial limitation but it also fails after the first payment.

**Comment by cbrwizard** [comment]
Hey, thank you for your report, I'll investigate this today

**Comment by cbrwizard** [comment]
Apparently it was an issue on our server unrelated with npm package. Please reinstall, it should just work.

**Comment by dmandrioli** [comment]
Hi Fyodor, I just retried (after removing node_modules) but I get the same error. Apparently it is not fixed :)

**Comment by dmandrioli** [comment]
I'm sorry to complain again but I still get the error. Just in case it would be helpful I reproduce the Node error log:
```
59 info run @streamlinehq/streamlinehq@2.1.0 postinstall { code: 1, signal: null }
60 timing reify:rollback:createSparse Completed in 4ms
61 timing reify:rollback:retireShallow Completed in 0ms
62 timing command:install Completed in 799ms
63 verbose stack Error: command failed
63 verbose stack     at ChildProcess.<anonymous> (/home/hail/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.j
s:64:27)
63 verbose stack     at ChildProcess.emit (node:events:369:20)
63 verbose stack     at maybeClose (node:internal/child_process:1067:16)
63 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
64 verbose pkgid @streamlinehq/streamlinehq@2.1.0
65 verbose cwd /home/hail/icons_debug
66 verbose Linux 4.15.0-142-generic
67 verbose argv "/home/hail/.nvm/versions/node/v15.14.0/bin/node" "/home/hail/.nvm/versions/node/v15.14.0/bin/npm" "i"
68 verbose node v15.14.0
69 verbose npm  v7.7.6
70 error code 1
71 error path /home/hail/icons_debug/node_modules/@streamlinehq/streamlinehq
72 error command failed
73 error command sh -c npm start
74 error > @streamlinehq/streamlinehq@2.1.0 start
74 error > node build/index.js
74 error
74 error Installing Streamline assets for kameleon families
74 error Error
75 error Error: Got error "unable to process request at this time"
75 error     at /home/hail/icons_debug/node_modules/@streamlinehq/streamlinehq/build/index.js:1:4437
75 error     at /home/hail/icons_debug/node_modules/@streamlinehq/streamlinehq/build/index.js:1:1702
75 error     at Object.next (/home/hail/icons_debug/node_modules/@streamlinehq/streamlinehq/build/index.js:1:1807)
75 error     at i (/home/hail/icons_debug/node_modules/@streamlinehq/streamlinehq/build/index.js:1:546)
75 error     at processTicksAndRejections (node:internal/process/task_queues:94:5)
76 verbose exit 1

```

**Comment by cbrwizard** [comment]
Oops the issue was closed for the second time by a mistake, I'm still investigating :O

**Comment by cbrwizard** [comment]
Turned out there was another issue on our server on top of the previous one. I was able to install those new families. Please check again!

**Comment by dmandrioli** [comment]
It works as expected now. Thanks!
